import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../../components/layout/Navbar'
import Home_Page from '../../components/layout/Home_Page'
import Categories from '../../components/product/Categories'
import FeaturedProducts from '../../components/product/FeaturedProducts'
import Footer from '../../components/layout/Footer'
import axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ featuredProducts }) {
  return (
    <>
      <Head>
        <title>Sneaker Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
      <Navbar />
      <Home_Page />
      <Categories />
      <FeaturedProducts products={featuredProducts} />
      <Footer />
      </>
    </>
  )
}


export async function getServerSideProps(){
  const { data } = await axios.get(`https://sneaker-store-six.vercel.app/api/products`)


  return {
    props: {
      featuredProducts: data
    }
  }
}