const data = {
  products: [
    {
      name: "Nike X-Trainer",
      desc: "A breathable cross training shoe, lightweight and durable.",
      category: "Mens",
      price: 122.59,
      image: "/assets/nike_grey_trainer_1.jpg",
      featured: true,
    },
    {
      name: "Asics Gel Nimbus 4",
      desc: "Designed to feel like you are running on clouds, the Gel Nimbus offers superior comfort with strong performance.",
      category: "Womens",
      price: 212.99,
      image: "/assets/asics_womens.jpg",
      featured: true,
    },
    {
      name: "Asics GT-2000 1",
      desc: "A stable running experience and a responsive underfoot feel.",
      category: "Mens",
      price: 244.89,
      image: "/assets/asics_womens.jpg",
      featured: false,
    },
    {
      name: "Adidas Pureboost",
      desc: "Boost your running game with Pureboost technology.",
      category: "Mens",
      price: 180.0,
      image: "/assets/adidas_pureboost.jpg",
      featured: false,
    },
    {
      name: "Cloudtec Ultrarunner",
      desc: "Go the distance with our Ultrarunner model, designed to help you push your limits.",
      category: "Mens",
      price: 313.99,
      image: "/assets/cloudtec_mens.jpg",
      featured: true,
    },
    {
        name: "Saucony Variance III",
        desc: "Unleash your potential with our third iteration of the popular Variance model.",
        category: "Mens",
        price: 199.99,
        image: "/assets/saucony_men.jpg",
        featured: false,
      },
        {
        name: "Sketchers M-Strike",
        desc: "Strike the trails with the M-Strike, with the patented Resalyte technology to aid in your journey.",
        category: "Mens",
        price: 127.79,
        image: "/assets/sketchers_mens.jpg",
        featured: false,
      },
      {
        name: "Saucony Transcend II",
        desc: "Transcend boundaries with this innovative shoe, giving you premium performance.",
        category: "Womens",
        price: 182.99,
        image: "/assets/saucony_transcend_women.jpg",
        featured: true,
      },
    {
      name: "Nike Kids Runner",
      desc: "A trainer designed for your child, a blend between comfort and results.",
      category: "Children",
      price: 99.99,
      image: "/assets/nike_kids.jpg",
      featured: true,
    },
    {
      name: "Asics Junior Runner I",
      desc: "Big things come in small packages, this sneaker is no exception.",
      category: "Children",
      price: 72.0,
      image: "/assets/multi_colour_toddler.jpg",
      featured: false,
    },
  ],
};

export default data;
